default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: docker
  password: docker
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rotabot_development

test:
  <<: *default
  database: rotabot_test

production:
  <<: *default
  database: rotabot_production
